steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/kubernetes-428622/container1", "."]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/kubernetes-428622/container1"]

  # Step to apply the deployment for Container 1
  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER --zone $CLOUDSDK_COMPUTE_ZONE && kubectl apply -f deployment-container1.yaml",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a" # Set to your cluster's zone
      - "CLOUDSDK_CONTAINER_CLUSTER=assignment-cluster" # Set to your cluster's name

images:
  - "gcr.io/kubernetes-428622/container1"

options:
  logging: CLOUD_LOGGING_ONLY
