apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-deployment-container1
  labels:
    app: test-assignment
    component: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-assignment
      component: container1
  template:
    metadata:
      labels:
        app: test-assignment
        component: container1
    spec:
      volumes:
        - name: assignment-pv-storage
          persistentVolumeClaim:
            claimName: assignment-pv-claim
      containers:
        - name: container1
          image: gcr.io/kubernetes-428622/container1:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: assignment-pv-storage
              mountPath: /usr/share/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-container1
spec:
  type: LoadBalancer
  selector:
    app: test-assignment
    component: container1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
